z5Frontend/grails-app/controllers/com/deerwalk/z5/CmsController.groovy
package com.deerwalk.z5




class CmsController {
    def displayService

    def index() {
        render (view: "../dashboard/index",model:[isEditable:true] )
    }

    def highPharmacy() {
        render (view: "../highPharmacyCost/index",model:[isEditable:true] )
    }
    def drugsDetails(){
        render (view: "../highPharmacyCost/drugsDetails",model:[isEditable:true,type:params.type] )
    }
    def erUtilization() {
        render (view: "../erUtilization/index",model:[isEditable:true] )
    }
    def populationRisk() {
        render (view: "../populationRisk/index",model:[isEditable:true] )
    }

    def setClient(){
        render (view: "../dashboard/setClient",model:[isEditable:true] )
    }


    def uiTracker() {
        render (view: "../UITracker/list",model:[isEditable:true] )
    }

    def costDriversDetails(){
        render (view: "../erUtilization/costDriversDetails",model:[isEditable:true] )
    }
    def topChronicDetails(){
        render (view: "../erUtilization/topChronicDetails",model:[isEditable:true] )
    }
    def telemedicine(){
        render (view: "../erUtilization/telemedicine",model:[isEditable:true] )
    }

    def costSharing(){
        render (view: "../erUtilization/costSharing",model:[isEditable:true] )
    }

    def communicateOptions(){
        render (view: "../erUtilization/communicateOptions",model:[isEditable:true] )
    }
    def expandUrgent(){
        render (view: "../erUtilization/expandUrgent",model:[isEditable:true] )
    }

    def gapInCare(){
        render (view: "../dashboard/gapInCare",model:[isEditable:true] )

    }

    def networkUse(){
        render (view: "../networkUse/index",model:[isEditable:true] )

    }
    def imagingService(){
        render (view: "../dashboard/imaging",model:[isEditable:true] )

    }

    def updateData(){
        try{
            displayService.insertContent(params.code,params.value,params.url)
        }catch(Exception e){
            println "Error occured while updating config file;e="+e.toString()
        }
        render true
    }

    def strategicPage(){
        render (view: "../highPharmacyCost/strategicPage",model:[isEditable:true] )

    }
}

z5Frontend/grails-app/controllers/com/deerwalk/z5/DashboardController.groovy
package com.deerwalk.z5

import com.deerwalk.security.ClientLogo
import com.deerwalk.security.ClientLogoConfiguration
import com.deerwalk.security.DwClient
import com.deerwalk.security.User
import grails.converters.JSON
import org.codehaus.groovy.grails.web.json.JSONArray
import org.codehaus.groovy.grails.web.json.JSONObject
import org.springframework.web.multipart.MultipartFile
import org.springframework.web.multipart.MultipartHttpServletRequest

//@Mixin(HighPharmacyCostController)
class DashboardController {

    def springSecurityService
    def messageSource
    def localeResolver
    def displayService
    def fetchService
    def dashBoardChartService
    def helperService
    def accountSettingsService
    def grailsApplication
    def populationRiskService
    def memberDrillService
    def mailService
    def dynamicParamsGeneratorService
    def groovyPageRenderer

    /*def client(){
        session.client="ims"
        render "session=>"+session.client
    }*/



    def reportingDetail(){
//        def currentMap=servletContext.getAt("parameters");
        def reportingDates=helperService.getReportingDates(session.ceDate)
        params.reportingFrom=reportingDates.currentFrom
        params.reportingTo=reportingDates.currentTo
//        params.range=params.range
//        params.reportingBasis=params.reportingBasis
//        params.clientId=servletContext.getAt("clientIdentity")
        def dynamicReportParam = dashBoardChartService.setDynamicReportParams(params,session,[:])
        def dataGraph = dashBoardChartService.getDashBoardChartScript(dynamicReportParam,"featureInfo")
        params.eligibleMemberCount=dataGraph.featureInfo.eligibleMemberCount
        params.overAllMemberCount=dataGraph.featureInfo.overAllMemberCount
//        params.isExclude=(params.isExclude=="true")?"Excluding":"Including"
        params.isExclude=(params.isExclude=="true")?true:false
//        currentMap.range=params.range
//        currentMap.isExclude=params.isExclude
        if(session.clientname){
            def client=DwClient.findByName(session.clientname)
//            params.groupName=client.description

        }

        render(template: "reportingDetails",model:[parameters:params])
    }



    def index() {
//        applicationContext.getBean("displayService");


        def dashBoardParams = session.dashBoardParams?:[:]
        dashBoardParams.reportingBasis="PaidDate"
        def reportingDates;
        def data
        if(session.ceDate){
            dashBoardParams.csDate=session.csDate
            dashBoardParams.ceDate=session.ceDate
            reportingDates=helperService.getReportingDates(dashBoardParams.ceDate)
            dashBoardParams.reportingFrom=reportingDates.currentFrom
            dashBoardParams.reportingTo=reportingDates.currentTo
//            dashBoardParams.clientId=servletContext.getAt("clientIdentity")
            def dynamicReportParams = dashBoardChartService.setDynamicReportParams(dashBoardParams,session,[:])
            data = dashBoardChartService.getDashBoardChartScript(dynamicReportParams,"groupMemberCountView")
            if(!data) data=[:]


            if(session.clientname){
                def client=DwClient.findByName(session.clientname)
                if(data){
                    data.groupDetail.groupName=client.description
                }
            }
        }else{
            data=[:]
        }
        [isEditable:false,group:data?.groupDetail]
    }

    def getChartScriptForDashBoard(){
        def chartType=params.chart
        def dashBoardParams = session.dashBoardParams?:[:]


        dashBoardParams.reportingBasis="PaidDate"
        dashBoardParams.csDate=session.csDate
        dashBoardParams.ceDate=session.ceDate

        def reportingDates=helperService.getReportingDates(dashBoardParams.ceDate)
        dashBoardParams.reportingFrom=reportingDates.priorFrom
        dashBoardParams.reportingTo=reportingDates.currentTo
        dashBoardParams.range="0"
        dashBoardParams.isExclude="false"
//        dashBoardParams.clientId=servletContext.getAt("clientIdentity")
        def dynamicReportParams = dashBoardChartService.setDynamicReportParams(dashBoardParams,session,[:])

        def data;
        try{
            if(chartType=="render1") data = dashBoardChartService.getDashBoardChartScriptWBenchmark(dynamicReportParams,"pharmacyClaimsPmpm")
            if(chartType=="render2") data = dashBoardChartService.getDashBoardChartScriptWBenchmark(dynamicReportParams,"medicalClaimsPmpm")
            if(chartType=="render3"){
                dashBoardParams.reportingFrom=reportingDates.currentFrom
                dashBoardParams.reportingTo=reportingDates.currentTo
                dynamicReportParams=dashBoardChartService.setDynamicReportParams(dashBoardParams,session,[:])
                data = dashBoardChartService.getDashBoardChartScript(dynamicReportParams,"populationRisk")
                dashBoardParams.pastMonth=reportingDates.pastMonth
                memberDrillService.getPopulationRiskDashParams(data,true,'member',dashBoardParams)


            }
            if(chartType=="render4"){
                dashBoardParams.reportingFrom=reportingDates.currentFrom
                dashBoardParams.reportingTo=reportingDates.currentTo
//                dynamicReportParams=dashBoardChartService.setDynamicReportParams(dashBoardParams,session,[:])
//                data = dashBoardChartService.getDashBoardChartScript(dynamicReportParams,"populationRiskByTopChronicCondition")
            }

            if(chartType=="render1"){
                def dataPh=data.getAt('reporting')
                def dataBm=data.getAt('benchmark').getAt("Pharmacy Claims PMPM")
                data=dataPh
                data.benchmark=dataBm
            }

            if(chartType=="render2"){
                def dataPh=data.getAt('reporting')
                def dataBm=data.getAt('benchmark').getAt("Medical Claims PMPM")
                data=dataPh
                data.benchmark=dataBm
            }
            if(chartType=="render3"){
                data.fromDate=reportingDates.currentFrom
                data.toDate=reportingDates.currentTo
            }

            render data as JSON

        }catch(e){
            log.error(e.getMessage())
            render status: 204;
        }

    }

    def changePasswd(){}

    def setClient(){
        //only enabled for navigation client
        /* String requestHost = request.getHeader('Host')

         def clientName=requestHost.toString().split("\\.")[0];
         if(clientName!=grailsApplication.config.grails.navigationUrl){
             redirect(controller: "dashboard",action: "index")
         }*/
        if(params.client){
//            println "springSecurityService = "+springSecurityService?.principal?.id

            def user=User.findById(springSecurityService?.principal?.id)
//          springSecurityService.reauthenticate()
            def dwClients=params.client
            session.clientname=dwClients
            if(!params.url || params.client=="usermanagement"|| params.client=="usermanagement_dev"){
                params.url="";
            }
//            SpringSecurityUtils.reauthenticate user.username, null
            def url="${grailsApplication.config.grails.protocol}://"+dwClients+"${grailsApplication.config.grails.hostPath}"+params.url;
            redirect(url: url)
        }else{
            def user=User.findById(springSecurityService?.principal?.id)
            ArrayList<DwClient> clients=user.clients.sort{it.name}
            def bob=clients.find{it.name==grailsApplication.config.grails.navigationUrl}
            if(bob){
                clients.remove(bob)
            }

            if(clients.size()==1){
                def url="${grailsApplication.config.grails.protocol}://"+clients[0].name.toLowerCase()+"${grailsApplication.config.grails.hostPath}";
                redirect(url: url)
            }else{
                [clients:clients,isEditable:false]
            }

        }

    }


    def viewForClientGroup(){
        /*String requestHost = request.getHeader('Host')
        println "requestHost = $requestHost"
        def clientName=requestHost.toString().split("\\.")[0];
        def clientView=false;
        if(clientName==grailsApplication.config.grails.bobUrl){
            clientView=true;
        }
        def user=User.findById(springSecurityService?.principal?.id)
        def appendList="";
        if(clientView){
            def clients=user.clients.sort{it.name}
            appendList="<ul>";
//            clients.each {
                appendList+= "<li class=\"clientSelect\" onclick=\"clientSelect(this)\"><a href=\"#\">Group I</a></li>\n";
                appendList+= "<li class=\"clientSelect\" onclick=\"clientSelect(this)\"><a href=\"#\">Group J</a></li>\n";
//            }
            appendList+="</ul>";
        }else{
            appendList="";

            *//*" <ul>\n" +
                    "        <li class=\"groupSelect ${session.group['Group I'] == '1' ? 'active' : ''}\"><a href=\"#\">Group I</a></li>\n" +
                    "        <li class=\"groupSelect ${session.group['Group J'] == '1' ? 'active' : ''}\"><a href=\"#\">Group J</a></li>\n" +
                    "        </ul>"*//*
        }*/

        def user=User.findById(springSecurityService?.principal?.id)
        ArrayList<DwClient> clients=user.clients.sort{it.name}
        def bob=clients.find{it.name==grailsApplication.config.grails.navigationUrl}
        if(bob){
            clients.remove(bob)
        }
//        def clients=user.clients.sort{it.name}
        render(template: "clientBox",model:[clients:clients,url:params.url.toString().trim()])
    }

    def selectGroup(){
        session.group[params.id]=params.flag
        session.group.each{key,val->
            if(key==params.id){
                session.group[key]=params.flag
            }else{
                session.group[key]=0
            }

z5Frontend/grails-app/views/dashboard/_clientBox.gsp
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta content="main" name="layout" />
    <title>Choose Clients</title>
    <script>
        function selectClients(){
            var client=$("#client").val();
            if(!client) return false

            $("#reloadForm").submit();
            /*jQuery.ajax({
             type:'POST',
             data:{client:client},
             async:false,
             url:'%{--<g:createLink controller="dashboard" action="reloadClient"/>--}%',
             success:function(resp){
             var url="http://"+resp+".deerwalk.local:9090/z5";
             alert(url);
             window.location.target=url
             },
             error:function(XMLHttpRequest,textStatus,errorThrown){
             },
             complete:function(XMLHttpRequest,textStatus){
             }});*/

        }
    </script>
</head>
<body>
<div class="contentWrapper" >



    <body>

    <div class="col-md-12 text-center">
        <h3 class="weltitle mb15">
            <span class="isEditable"><g:editMessage code="dashboard.setClient.head"/></span>
        </h3>
        <g:if test="${flash.message}" >
            <div class="alert alert-warning" >${flash.message}</div>
        </g:if>
        <g:if test="${!flash.error}">
            <g:form name="reloadForm"  action="setClient">
                <div id="wrapper_bg">
                    <span class="isEditable"><g:editMessage code="dashboard.setClient.title"/></span>
                    <g:hiddenField name="url" value="${url}"/>
                    :
                    %{--<g:select name="client" from="${clients}" optionKey="name" optionValue="name" noSelection="['':'Select Clients']" onchange="selectClients()"/>--}%
                    <g:select name="client" class="clientSelect" from="${clients}" optionKey="name" optionValue="description" noSelection="['':'Select One']"/>

                    &nbsp;
                    <button name="saveG" value="Go" class="btn btn-link-upper btn-primary" style="margin-top: -3px;" onclick="selectClients()">
                        <span class="isEditable">
                            Go
                        </span>
                    </button>
                </div>
            </g:form>

        </g:if>

    </div>
</div>
</body>
</html>

z5Frontend/grails-app/views/dashboard/_clientInfo.gsp
<div class="col-md-11" style="margin-bottom:12px;">
        <div class="pull-right">
            <span><span style="color: steelblue;">Viewing Client :</span> <span class="color-gray">
                <g:editMessage code="client.${session.clientname}"/>
            </span></span> &nbsp;
            <img class=" bordered autoImage pull-right" src="${createLink(controller:'dashboard', action:'clientLogo')}" />
        </div>
</div>

z5Frontend/grails-app/views/dashboard/_cohortMailTemplate1.gsp
<%@ page contentType="text/html" %>
<html>
<head>
    <title>Mail</title>
    <link rel="stylesheet" type="text/css" href="${resource(dir: 'css', file: 'layout.css')}">
    <link rel="stylesheet" type="text/css" href="${resource(dir: 'bootstrap/css', file: 'bootstrap.min.css')}">
</head>

<body>
<div class="mainWrapper">
    <div class="container">
        <div class="col-md-12">

            Hello Team,<br>
            This is a new cohort request from ${name} for group - ${client}. The details are as follows:
            <br>
            <br>



    <div class="z5-table">
        <table width="80%" border="0" cellspacing="5" cellpadding="5">

            <tbody>

            <tr>
                <td width="20%"></td>
                <td width="15%" style="text-align: right">User</td>
                <td ><a href="mailto:${user}" target="_top">${user}</a></td>
            </tr>

            <tr>
                <td ></td>
                <td style="text-align: right">Cohort Name</td>
                <td >${cohortName}</td>
            </tr>


            <tr>
                <td></td>
                <td style="text-align: right">Cohort Desc</td>
                <td>${cohortDesc}</td>
            </tr>

            </tbody>

        </table>
        <br>
        <br>
            Sincerly,<br> Z5 Support
    </div>
    </div>
    </div>

</div>




</body>
</html>

z5Frontend/grails-app/views/dashboard/_reportingDetails.gsp
<html xmlns="http://www.w3.org/1999/xhtml">
<div class="col-md-12"><div class="reporting-detail-wrapper"><table border="0" class="reportingD_details" width="100%">
    <tr>
        <td class="report-label" style="width: 195px;">Reporting Period :</td>
        <td style="width: 140px;"><g:formatDate format="MMM yyyy" date="${Date.parse('yyyy-MM-dd', parameters.reportingFrom)}"/> to <g:formatDate format="MMM yyyy" date="${Date.parse('yyyy-MM-dd', parameters.reportingTo)}"/> </td>
        %{--<td class="report-label">Reporting Through :</td>  <td><g:formatDate format="MMM yyyy" date="${Date.parse('yyyy-MM-dd', parameters.reportingTo)}"/> </td>--}%
        <td class="report-label" style="width: 116px;" >Reporting Basis :</td> <td style="width: 60px;">${parameters.reportingBasis=="PaidDate"?"Paid":"Incurred"}</td>

        <td class="report-label" style="width: 270px;">Excluding population with cost greater than : </td>
        <td style="width:50px;">
        <g:if test="${parameters?.range}">
                <g:if test="${parameters.range.toInteger()<=0 || !parameters.isExclude}">
                    None
                </g:if><g:else>
                $ ${parameters.range.toInteger()/1000} k
            </g:else>
        </g:if><g:else>
            None
        </g:else>

        </td>

        <td rowspan="2" class="viewing-sep" style="width: 223px;">
                Viewing Client :<br>

                %{--<g:editMessage code="client.${session.clientname}"/>--}%
            %{--<img class="autoImage profile-img" src="${createLink(controller:'dashboard', action:'clientLogo')}" />--}%
            ${params.groupName}
            <a href="#" class="reporting-detail-toggle toggle-expanded">
                &nbsp;<i class="fa fa-chevron-up"></i>&nbsp;
            </a>
        </td>
        </tr>
    <tr>
        <td class="report-label">Members with Enrollment Info :</td><td>${parameters.overAllMemberCount}</td>

        <td class="report-label">Active Members :</td><td> ${parameters.eligibleMemberCount}</td>
                <td colspan="2"></td>


        %{-- <td colspan="2" class="text-left">
             Viewing Client : <g:editMessage code="client.${session.clientname}"/>


         </td>--}%
    </tr>

</table></div></div>

</html>
%{--

--}%

z5Frontend/grails-app/views/dashboard/checkUrl.gsp
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="layout" content="main" />
</head>
<body>
<div class="contentWrapper" >
<ul style="margin-left: 25px;list-style: outside!important;">
    <g:if test="${urls}">
        <g:set value="${urls.size()}" var="numberOfUrls"></g:set>
        <g:each in="${urls}" var="url" status="i">
            <li style="list-style: decimal!important;">
                <g:if test="${(i+1)==(numberOfUrls)}">
                    <span style="color:#ff3300!important;">${url.split('::')[0]}::${url.split('::')[1]}::</span>
                    <g:link controller="request" action="viewResponse" style="color:#ff3300!important;" params="[url: url.split('::')[2]]">${url.split('::')[2]}</g:link>
                    <br><br>
                </g:if>
                <g:else>
                    <span style="color:#000!important;">${url.split('::')[0]}::${url.split('::')[1]}::</span>
                    <g:link controller="request" style="color:#000!important;" action="viewResponse" params="[url: url.split('::')[2]]">${url.split('::')[2]}</g:link>
                    <br><br>
                </g:else>
            </li>
        </g:each>
        </ul>
    </g:if>
    <div style="float:right; margin-right: 30px; margin-bottom: 15px;">
        <g:form action="checkUrl" method="post">
            <g:hiddenField name="clearAll" value="true"/>
            <input type="submit" value="Clear All">
        </g:form>
    </div>
</div>
</body>
</html>

z5Frontend/grails-app/views/dashboard/gapInCare.gsp
<%--
  Created by IntelliJ IDEA.
  User: nisharma
  Date: 12/17/2015
  Time: 11:45 AM
--%>
<%@ page import="grails.converters.JSON" contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="layout" content="main">
    <title>Gap In Care</title>
    <g:if test="${isEditable}">
        <meta name="layout" content="mainCms">
    </g:if>
    <g:else>
        <meta name="layout" content="main">
    </g:else>
</head>

<body>


<div  id="contentWrapper" class="contentWrapper">

    <div class="container double-arrow-back-top-container">
        <div class="col-md-6 double-arrow-back-top">
        <span class="isEditable"> <g:link controller="dashboard" action="index" class="text-link-upper mb15 double-arrow-left">
                                <g:editMessage code="gapInCare.allCostDrivers"/>
            </g:link></span>
        </div>
        <div class="col-md-6" style="display: none;" id="editContent">
            <li>
            <sec:ifAllGranted roles="ROLE_Z5ADMIN">
                <g:if test="${!isEditable}">
                    <g:link title="Edit Content"  controller="cms" action="gapInCare"><i class="fa fa-edit"></i> Edit Content</g:link>
                </g:if><g:else>
                <g:link title="View Changes"  controller="dashboard" action="gapInCare"><i class="fa fa-eye"></i> View Changes</g:link>
                </g:else>
            </sec:ifAllGranted>
            </li>
        </div>



        <%
            //        split page
        %>



        <div class="col-md-12">
            <h2 class="mb15">
                <g:img uri="/images/icon-high-cost-claimants.png" class="heading-icon"/>
                <span class="isEditable"><g:editMessage code="gapInCare.title"/></span></h2>
        </div>
        <div class="clearfix"></div>

        <div class="sep-border mb25 "></div>

        <div class="col-md-12 text-right">
            <a href="#" class=" custom-tooltip text-link-upper iconExploreEntirePopulation"><g:img uri="/images/icon-explore-population.png" alt=""/><span class="isEditable"><g:editMessage code="gapInCare.explore.population"/></span><input type="hidden" value="hPharmacy.container3.table1.options1"></a>
            <a href="#"  class="custom-tooltip text-link-upper iconExportCSV"><g:img uri="/images/icon-dwonload-data.png" alt=""/><span class="isEditable"><g:editMessage code="gapInCare.export.csv"/></span><input type="hidden" value="hPharmacy.container3.table1.options2"></a>
        </div>

            <div class="col-md-6">
                <h6 class="has-filter">
                <span id="graph1Filter">
                    <g:if test="${!isEditable}">
                        Compare <span style="color: steelblue;"><g:select style="width:80px;" name="reportingBasis1"
                                                                          from="${['PaidDate': 'paid', 'ServiceDate': 'incurred']}"
                                                                          optionKey="key" optionValue="value"
                                                                          onchange="refreshReport()"/></span>
                        claims </span>
                        that <span style="color: steelblue;"><g:select style="width:75px;" name="includeOn"
                                                                   from="${['false': 'include', 'true': 'exclude']}"
                                                                   optionKey="key" optionValue="value"
                                                                   onchange="refreshReport()"/></span>
                        cases over <span style="color: steelblue;"><g:select style="width:65px;" name="range1"
                                                                             from="${['0': '$0', '10000': '$10 k', '25000': '$25 k', '50000': '$50 k', '100000': '$100 k']}"
                                                                             optionKey="key" optionValue="value"
                                                                             onchange="refreshReport()"/></span>
                        per year
                    </g:if>
                </h6>
            </div>

        <div class="has-filter col-md-6">
            <span class="f-right custom-tooltip">
                <span class=" isEditable " ><g:editMessage code="gapInCare.container1.methodology" /></span>
                <span class="fa fa-chevron-right " onclick="displayData('methodology2')"></span>
            </span>

        </div>



        <div  class="col-md-12">
            <g:if test="${!isEditable}">
                        <g:render template="gapInCareTable" />
            </g:if>
        </div>
        %{--<div  class=" z5-table put-border">

                <table width="100%" border="0" cellspacing="0" cellpadding="0" class="z5-fixed-header" >
                <thead>
                <tr>
                    <th>Category</th>
                    <th>Metric</th>
                    <th>Member In Group</th>
                    <th>Meeting Metric</th>
                    <th>Not Meeting Metric</th>
                    <th>%</th>

                    --}%%{--<th>Metric Type</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Category</th>
                    <th>Population</th>
                    <th>Numerator</th>--}%%{--
                </tr>
                </thead>
                <tbody>
                <g:each  in="${careFor}" var="data">
                    <tr>
                        <td style="text-transform: capitalize">${data.value.metricType}</td>
                        <td>${data.value.name}</td>
                        <td>${data.value.description}</td>
                        <td>${data.value.category}</td>
                        <td>${data.value.population}</td>
                        <td>${data.value.numerator}</td>
                    </tr>
                </g:each>
                </tbody>
            </table>
        </div>--}%

    </div>
    <%
        //        split page
    %>
</div>
<link rel="stylesheet" type="text/css" href="${resource(dir: 'css', file: 'graph2.css')}">

<script language="javascript" type="text/javascript" src="${resource(dir: 'js', file: 'jquery.floatThead.min.js')}"></script>
<script>
    $(document).ready(function() {
        var $table = $('table.z5-fixed-header');
        $table.floatThead({
            scrollContainer: function ($table) {
                return $table.closest('.z5-table');
            }
        });

    });

    function refreshReport() {
        var reportingBasis, fromDate, range, isExclude;
        reportingBasis = $("#reportingBasis1").val();
//            fromDate = $("#fromDate1").val();
        isExclude = $("#includeOn").val();
        range = ($("#range1").val());

        jQuery.ajax({
            type: 'POST',
            data: {reportingBasis: reportingBasis, range: range, isExclude: isExclude, module: 'lineGraph1'},
            url: '<g:createLink controller="dashboard" action="gapInCare"/>',
            success: function (resp) {
                $("#gapInCareSec").html(resp);

            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
            },
            complete: function (XMLHttpRequest, textStatus) {
            }
        });

    }
</script>
</body>
</html>

z5Frontend/grails-app/views/dashboard/setClient.gsp
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <g:if test="${isEditable}">
        <meta name="layout" content="mainCms">
    </g:if>
    <g:else>
        <meta name="layout" content="main">
    </g:else>

    <title>Choose Clients</title>
    <script>
        function selectClients(){
            var client=$("#client").val();
            if(!client) return false

            $("#reloadForm").submit();
            /*jQuery.ajax({
             type:'POST',
             data:{client:client},
             async:false,
             url:'%{--<g:createLink controller="dashboard" action="reloadClient"/>--}%',
             success:function(resp){
             var url="http://"+resp+".deerwalk.local:9090/z5";
             alert(url);
             window.location.target=url
             },
             error:function(XMLHttpRequest,textStatus,errorThrown){
             },
             complete:function(XMLHttpRequest,textStatus){
             }});*/

        }
    </script>
</head>
<body>
<div class="contentWrapper" >





    <div class="container">
        <g:hiddenField name="showReportingDetails" value="false"/>
        <div style="display: none;" id="editContent">
            <li>
        <sec:ifAllGranted roles="ROLE_Z5ADMIN">
            <g:if test="${!isEditable}">
                <g:link controller="cms" action="setClient" title="Edit Content" ><i class="fa fa-edit"></i> Edit Content</g:link>
            </g:if><g:else>
            <g:link controller="dashboard" action="setClient" title="View Changes" ><i class="fa fa-eye"></i> View Changes</g:link>
        </g:else>
        </sec:ifAllGranted>
                </li>
            </div>
        <div class="col-md-12 text-center">
            <h3 class="weltitle mb15">
                <span class="isEditable"><g:editMessage code="dashboard.setClient.head"/></span>
                </h3>
            <g:if test="${flash.message}" >
                <div class="alert alert-warning" >${flash.message}</div>
            </g:if>
            <g:if test="${!flash.error}">
                <g:form name="reloadForm"  action="setClient">
                    <div id="wrapper_bg">
                        <span class="isEditable"><g:editMessage code="dashboard.setClient.title"/></span>
                        :
                    <g:if test="${!isEditable}">
                        <g:select name="client" class="clientSelect" from="${clients}" optionKey="name" optionValue="description" noSelection="['':'Select One']" />
                        &nbsp;
                        <button name="saveG" value="Go" class="btn btn-link-upper btn-primary" style="margin-top: -3px;" onclick="selectClients()">
                            <span class="isEditable">
                               Go
                            </span>
                        </button>
                    </g:if>
                        %{--<g:select name="client" from="${clients}" optionKey="key" optionValue="value" noSelection="['':'---Select---']" onchange="selectClients()"/>--}%
                    </div>
                </g:form>

            </g:if>
        </div>


    </div>
</div>
</body>
</html>