z5Frontend/grails-app/controllers/com/deerwalk/z5/PopulationRiskController.groovy
package com.deerwalk.z5

import grails.converters.JSON
import org.codehaus.groovy.grails.web.json.JSONObject

class PopulationRiskController {

    def populationRiskService
    def helperService
    def fetchService
    def reportFactoryService
    def memberDrillService
    def exportService
    def dashBoardChartService
    def searchService

    def dynamicParamsGeneratorService
    def reportFetchService

    def riskChart={
        def dashBoardParams = session.dashBoardParams?:[:]
        dashBoardParams.reportingBasis="PaidDate"
        dashBoardParams.csDate=session.csDate
        dashBoardParams.ceDate=session.ceDate

        def reportingDates=helperService.getReportingDates(dashBoardParams.ceDate)
        dashBoardParams.reportingFrom=reportingDates.priorFrom
        dashBoardParams.reportingTo=reportingDates.currentTo
        dashBoardParams.range="0"
        dashBoardParams.isExclude="false"
        dashBoardParams.includes="[truvenBenchmark]"
        dashBoardParams.benchmarkKey="chronicConditionUtilization"

        def dynamicReportParams = dashBoardChartService.setDynamicReportParams(dashBoardParams,session,[:])

        def data;
        def newDataList=[:];
        try{
                dashBoardParams.reportingFrom=reportingDates.currentFrom;
                dashBoardParams.reportingTo=reportingDates.currentTo;
                dynamicReportParams=dashBoardChartService.setDynamicReportParams(dashBoardParams,session,[:]);
                data = dashBoardChartService.getPopChartScript(dynamicReportParams,"populationRiskByTopChronicCondition");


            def newData=[:];

            JSONObject json=new JSONObject();
            if(params.modifiable){
                def modifiable=["1002","1005","1007","1008","1009","1011","1012","1016","1017","1021","1022","1023","metaInfo"]
                JSONObject map=new JSONObject();
                modifiable.each {
                    map[it]=data.reporting[it];
                }
                json['reporting']=map
                json['truvenBenchmark']=data['truvenBenchmark']
                data= json
            }

            data.reporting.each { id, datas ->
                if(id!="metaInfo")
                memberDrillService.getRisksDrillParams(datas,true,'member',dashBoardParams,"riskChart")
            }



//            datanew1['members_drill']=memberDrillService.getDiabetesCostsDrillParams(dataPh3,true,'member',params)
        }catch(e){
            log.error(e.getMessage())
            data=[status: 204];
        }

        [data:data,modifiable:params.modifiable]

    }


    def index() {
        session.zPop=[:]
        params.chronicCode=params.id?params.id:"1012"
        /*def topLineGraph=new ArrayList();
        def useOfErByChronicMembers=new ArrayList();
        def datanew1=[:];
        session.zPop=[:]
        params.trend="yearly"
//        params.metric="Diabetes"
//        params.chronicCode="1012"
        params.chronicCode=params.chronicCondition?params.chronicCondition:"1012"
        params.csDate=session.csDate
        params.ceDate=session.ceDate
        def reportingDates=helperService.getReportingDates(params.ceDate)
        params.reportingFrom=reportingDates.priorFrom
        params.reportingTo=reportingDates.priorTo

        params.reportingBasis="PaidDate"
        params.mbrRegionId=""
        params.clientId=3000
        params.range="0"
        session.zPop.range=params.range
        def dynamicReportParam = populationRiskService.setDynamicReportParams(params,session,[:])
        def dataGraph = populationRiskService.getPopulationRiskScriptWBenchmark(dynamicReportParam,"diabetesCost")
        def benchMarkValue=dataGraph.getAt('truvenBenchmark').getAt("Diabetes_pmpy")
        def neValue=benchMarkValue.toString().replace("\$","")
        neValue=neValue.toString().replace(",","")
        neValue=neValue.toDouble()
        datanew1=[:];
        def dataPh3=dataGraph.getAt('reporting')
        datanew1.benchmark=neValue
        datanew1.pmpy=dataPh3.getAt('chronicInfo').getAt("pmpy")
        datanew1.reportingDates=["reportingFrom":dynamicReportParam.reportingFrom,"reportingTo":dynamicReportParam.reportingTo]
        topLineGraph.add(datanew1)
        datanew1=[:];
        dynamicReportParam = populationRiskService.setDynamicReportParams(params,session,[:])
//        dataGraph = populationRiskService.getPopulationRiskScript(dynamicReportParam,"useOfErByChronicMembers")
        dataGraph = populationRiskService.getPopulationRiskScript(dynamicReportParam,"newUseOfErByChronicMembers")
        dataGraph.chronicConditions.total.year=Date.parse("yyyy-MM-dd", params.reportingTo)
//        useOfErByChronicMembers.add(dataGraph.erVisitInfoByChronicMembers)
        useOfErByChronicMembers.add(dataGraph.chronicConditions.total)


//        params.reportingFrom=reportingDates.pastFrom
//        params.reportingTo=reportingDates.pastTo

        params.reportingFrom=reportingDates.pastFrom
        params.reportingTo=reportingDates.pastTo
        dynamicReportParam = populationRiskService.setDynamicReportParams(params,session,[:])
        dataGraph = populationRiskService.getPopulationRiskScriptWBenchmark(dynamicReportParam,"diabetesCost")

        datanew1=[:];
        dataPh3=dataGraph.getAt('reporting')
        datanew1.benchmark=neValue
        datanew1.pmpy=dataPh3.getAt('chronicInfo').getAt("pmpy")
        datanew1.reportingDates=["reportingFrom":dynamicReportParam.reportingFrom,"reportingTo":dynamicReportParam.reportingTo]

        topLineGraph.add(datanew1)
        datanew1=[:];
        dynamicReportParam = populationRiskService.setDynamicReportParams(params,session,[:])
        dataGraph = populationRiskService.getPopulationRiskScript(dynamicReportParam,"newUseOfErByChronicMembers")
        dataGraph.chronicConditions.total.year=Date.parse("yyyy-MM-dd", params.reportingTo)
        useOfErByChronicMembers.add(dataGraph.chronicConditions.total)


        params.reportingFrom=reportingDates.currentFrom
        params.reportingTo=reportingDates.currentTo

        dynamicReportParam = populationRiskService.setDynamicReportParams(params,session,[:])
        dataGraph = populationRiskService.getPopulationRiskScriptWBenchmark(dynamicReportParam,"diabetesCost")
        datanew1=[:];
        dataPh3=dataGraph.getAt('reporting')
        datanew1.benchmark=neValue
        datanew1.pmpy=dataPh3.getAt('chronicInfo').getAt("pmpy")
        datanew1.reportingDates=["reportingFrom":dynamicReportParam.reportingFrom,"reportingTo":dynamicReportParam.reportingTo]
        topLineGraph.add(datanew1)
        datanew1=[:];
        dynamicReportParam = populationRiskService.setDynamicReportParams(params,session,[:])
        dataGraph = populationRiskService.getPopulationRiskScript(dynamicReportParam,"newUseOfErByChronicMembers")
        dataGraph.chronicConditions.total.year=Date.parse("yyyy-MM-dd", params.reportingTo)
        useOfErByChronicMembers.add(dataGraph.chronicConditions.total)

        datanew1=[:];
        def lineGraphR=[];
        params.reportingFrom=params.reportingTo
        params.reportingTo=helperService.addYear(params.reportingFrom)
        datanew1.put('year',params.reportingFrom)
        datanew1.put('actual',1000)
        lineGraphR.add(datanew1)
        datanew1=[:];
        datanew1.put('year',params.reportingTo)
        datanew1.put('actual',9900)
        lineGraphR.add(datanew1)
        def getMax=getMaximum(topLineGraph,lineGraphR)
        def yPercentage=0
        def yTotal=1

        params.reportingFrom=reportingDates.currentFrom
        params.reportingTo=reportingDates.currentTo
        dynamicReportParam = populationRiskService.setDynamicReportParams(params,session,[:])
        dataGraph = populationRiskService.getPopulationRiskScript(dynamicReportParam,"diabetesAlongOtherChronic")

        def barGraph=dataGraph
       // http://localhost:8080/DasTest/zakiPoint?clientId=3000&reportingBasis=PaidDate&reportingTo=2015-06-30
        // &reportingFrom=2014-07-01&eligibilityType=[medical]&report=recommendedCareForDiabetes&phiCSDate=01-01-2010&phiCEDate=06-30-2015
        params.reportingFrom=reportingDates.currentFrom
        params.reportingTo=reportingDates.currentTo
        dynamicReportParam = populationRiskService.setDynamicReportParams(params,session,[:])
        dataGraph = populationRiskService.getPopulationRiskScript(dynamicReportParam,"recommendedCareForDiabetes")
        def carePercent=dataGraph.getAt('metaInfo').getAt("percentOfNonCompliant")
        dataGraph.remove("metaInfo")
        def List<Object> careFor = new ArrayList<Object>();
        dataGraph.each { id, datas ->
            datas['members_drill']=memberDrillService.getDrillParams(datas,true,'member',params)
            careFor.add(datas)
        }
        careFor.sort{it.notMeeting}.reverse()

        useOfErByChronicMembers.sort{it.year}.reverse()
*/
        def chronicLists=[
                '1012': 'Diabetes',
                '1008': 'Congestive Heart Failure',
                '1005': 'CAD',
                '1002': 'Asthma',
                '1009': 'COPD',
                '1001': 'Affective Psychosis',
                '1003': 'Atrial Fibrillation',
                '1004': 'Blood Disorders',
                '1006': 'Cancer',
                '1007': 'Chronic Pain',
                '1010': 'Demyelinating Diseases',
                '1011': 'Depression',
                '1014': 'CKD',
                '1013': 'Eating Disorders',
                '1015': 'HIV/AIDS',
                '1016': 'Hyperlipidemia',
                '1017': 'Hypertension',
                '1018': 'Immune Disorders',
                '1019': 'Inflammatory Bowel Disease',
                '1020': 'Liver Diseases',
                '1021': 'Morbid Obesity',
                '1022': 'Osteoarthritis',
                '1023': 'Peripheral Vascular Disease',
                '1024': 'Rheumatoid Arthritis'
        ]

z5Frontend/grails-app/views/populationRisk/_tableDataDetails.gsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<div class="mb10"><span>
    %{--Your population with <span class="chronic-title">Diabetes</span> did not comply with Recommended Care of the time--}%

    <strong><g:formatNumber number="${carePercent}" maxFractionDigits="2"/> % </strong> of members have one or more gaps in care specific to <span class="chronic-title">{{chrc}}</span>%{--, resulting as much as <strong>[X]%</strong> higher costs compared to members with no gaps--}%
</span>
</div>
<div  class=" z5-table put-border">
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="z5-fixed-header" id="recommendedCareForDiabetes">
    <thead>
    <tr>
        <th class="text-left" style="height: 54px;">Category</th>
        <util:remoteSortableColumn  class="text-center"  property="membersInGroup" title="Members In Group (#)" update="barGraph2" action="sortResult" params="[module:'recommendedCareForDiabetes',chronicCode:chronicCode]" />
        <util:remoteSortableColumn  class="text-center ${defaultSort}"  property="percentMet" title="% Compliance" update="barGraph2" action="sortResult" params="[module:'recommendedCareForDiabetes',chronicCode:chronicCode]" />
        <util:remoteSortableColumn  class="text-center"  property="met" title="Met (#)" update="barGraph2" action="sortResult" params="[module:'recommendedCareForDiabetes',chronicCode:chronicCode]" />
        <util:remoteSortableColumn  class="text-center"  property="notMeeting" title="Not Met (#)" update="barGraph2" action="sortResult" params="[module:'recommendedCareForDiabetes',chronicCode:chronicCode]" />

        %{--<util:remoteSortableColumn   class="text-center ${defaultSort}"  property="notMeeting" title="% Not Meeting" update="barGraph2" action="sortResult" params="[module:'recommendedCareForDiabetes']" />--}%
        %{--<util:remoteSortableColumn style="width:110px;" class="text-center"  property="costPmpy" title="\$ PMPY" update="barGraph2" action="sortResult" params="[module:'recommendedCareForDiabetes',chronicCode:chronicCode]" />--}%
    </tr>
    </thead>
    <tbody>
    <g:each in="${careFor}" var="val">

        <tr>

            <td>${val?.description}</td>
            <td class="text-right">
                    ${val?.membersInGroup}
            </td>
            <td class="text-right"><g:formatNumber number="${val?.percentMet}" type="number" maxFractionDigits="1" />%</td>
            <td class="text-right">${val?.met} </td>
            <td class="text-right ">
                <g:z5Link class="color-red" disabledLink="${(val?.notMeeting)<=0?'true':'false'}" controller="memberSearch" action="searchResult" params="${val?.members_drill}">
                ${val?.notMeeting}</g:z5Link>
                %{--${(val?.notMeeting)<=0?'true':'false'}--}%
             </td>

            %{--<td  class="text-right">
                <g:formatZ5Currency number="${val?.costPmpy}" type="number" maxFractionDigits="2" />
            </td>--}%




            %{--<td class="text-right">${val?.met} </td>
            <td class="text-right"><g:formatNumber number="${val?.percentMet}" type="number" maxFractionDigits="0" />%</td>
            <td class="text-right"><g:formatNumber number="${val?.percentNotMeeting}" type="number" maxFractionDigits="0" />%</td>
--}%


        </tr>
    </g:each>
    </tbody>
</table>
    <script>
        $(document).ready(function () {
            var $table = $('table#recommendedCareForDiabetes');
            $table.floatThead({
                scrollContainer: function ($table) {
                    return $table.closest('.z5-table');
                }
            });

            chronicTitle=$("#chronicCondition option:selected").text();
            $(".chronic-title").html(chronicTitle);
        });
    </script>
</div>

z5Frontend/grails-app/views/populationRisk/_tableDataDetails2.gsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<div class="mb10"><span
        class=" isEditable">Spend for use of ER by members with
    <span class="chronic-title">{{chrc}}</span>
<strong>
    <g:if test="${percent<0}">
        decreased by
        <g:formatNumber number="${-1*percent}" maxFractionDigits="1"/> %

    </g:if><g:else>
        increased by <g:formatNumber number="${percent}" maxFractionDigits="1"/> %

    </g:else>

</strong>
    in the past 3 years.</span>
</div>
<div  class=" z5-table put-border">
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="z5-fixed-header" id="useOfErByChronicMembers">
    <thead>
    <tr>
        <util:remoteSortableColumn  class="${defaultSort}"  property="year" title="Year" update="barGraph3" action="sortResult" params="[module:'useOfErByChronicMembers',chronicCode:chronicCode]" />
        <util:remoteSortableColumn  class="text-center"  property="member" title="Chronic Condition Member Count" update="barGraph3" action="sortResult" params="[module:'useOfErByChronicMembers',chronicCode:chronicCode]" />
        <util:remoteSortableColumn  class="text-center"  property="erVisitor" title="Er Visited Chronic Condition Member Count" update="barGraph3" action="sortResult" params="[module:'useOfErByChronicMembers',chronicCode:chronicCode]" />
        <util:remoteSortableColumn   class="text-center "  property="erCost" title="Total ER Cost" update="barGraph3" action="sortResult" params="[module:'useOfErByChronicMembers',chronicCode:chronicCode]" />
        <util:remoteSortableColumn  class="text-center "  property="percentOfnonErVisitor" title="No Visit" update="barGraph3" action="sortResult" params="[module:'useOfErByChronicMembers',chronicCode:chronicCode]" />
        <util:remoteSortableColumn   class="text-center"  property="percentOfoneTimeVisitor" title="One Visit" update="barGraph3" action="sortResult" params="[module:'useOfErByChronicMembers',chronicCode:chronicCode]" />
        <util:remoteSortableColumn   class="text-center"  property="percentOftwoOrMoreTimesVisitor" title="Two Or More Visits" update="barGraph3" action="sortResult" params="[module:'useOfErByChronicMembers',chronicCode:chronicCode]" />
    </tr>
    </thead>
    <tbody>
    <g:each in="${useOfErByChronicMembers}" var="val">

        <tr>
            <td><g:formatDate format="yyyy" date="${val.year}"/>
            </td>
            <td  class="text-right">
                    ${val?.member}
               </td>
            <td  class="text-right">

                <g:z5Link disabledLink="${(val?.erVisitor)<=0?'true':'false'}" controller="memberSearch" action="searchResult" params="${val?.members_drill}">
                    ${val?.erVisitor}</g:z5Link>
               </td>
            <td class="text-right">
                <g:formatZ5Currency number="${val?.erCost}" type="number" maxFractionDigits="2" />

            </td>
            <td class="text-right"><g:formatNumber number="${val?.percentOfnonErVisitor}" type="number" maxFractionDigits="0" />%</td>
            <td class="text-right"><g:formatNumber number="${val?.percentOfoneTimeVisitor}" type="number" maxFractionDigits="0" />%</td>
            <td  class="text-right">
                <g:formatNumber number="${val?.percentOftwoOrMoreTimesVisitor}" type="number" maxFractionDigits="0" />%
            </td>

        </tr>
    </g:each>
    </tbody>
</table>
    <script>
        /*$(document).ready(function () {
            var $table = $('table#useOfErByChronicMembers');
            $table.floatThead({
                scrollContainer: function ($table) {
                    return $table.closest('.z5-table');
                }
            });

            chronicTitle=$("#chronicCondition option:selected").text();
            $(".chronic-title").html(chronicTitle);
        });*/
    </script>
</div>

z5Frontend/grails-app/views/populationRisk/popRiskDash.gsp
<%--
  Created by IntelliJ IDEA.
  User: nisharma
  Date: 7/21/16
  Time: 11:25 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="layout" content="main">
    <title>Population Risks</title>
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'bootstrap-silder.css')}" type="text/css">

</head>
<body>
<div class="contentWrapper">
    <g:hiddenField name="showReportingDetails" value="false"/>
    <div class="container">
        <div class="col-md-12 mt15">
            <span class="isEditable"><g:link controller="dashboard" action="index" class="text-link-upper mb15 double-arrow-left">
                All Cost Drivers

            </g:link></span>
        </div>
        <div class="col-md-12">
            <h2 class="mb15"><span class="isEditable">Risks Details - ${(params.id=='1')?"MARA":"HS"}</span></h2>
            <div class="sep-border mb15" ></div>
        </div>
        <div class="clearfix"></div>
        %{--<h3 style="text-align: center;"></h3>--}%
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div id="stackedGraph"></div>
        </div>
        <div class="col-md-2"></div>
        <div class="clearfix"></div>

    </div>
</div>
<div id="galleryImages1" style="display: none;;">
    <g:img dir="images" file="ajax-loader.gif" style="position:relative; top:50%;"/>
</div>


<script src="https://d3js.org/d3.v4.min.js"></script>
<script language="javascript" type="text/javascript" src="${resource(dir: 'js/dash', file: 'sankey.js')}"></script>

<script>


    refreshReport(${id});
//    var colores_g = {"highRisk":"#DC3912","medRisk":"#FF7F0E", "norRisk":"#E7BA52","lowRisk":"#2CA02C"};
    var colores_g = {"High":"#DC3912","Medium":"#FF7F0E", "Normal":"#E7BA52","Low":"#2CA02C"};


    function refreshReport(id) {
        $('#galleryImages1').show();
        var def = $.Deferred();
        jQuery.ajax({
            type: 'POST',
            data:{type:id},
            url: '<g:createLink controller="populationRisk" action="renderRiskSankey"/>',
            success: function (resp) {
                def.resolve(resp);

            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                def.reject();

//             $("networkTrendingSankey").html("No records to display");
            },
            complete: function (XMLHttpRequest, textStatus) {
            }
        });

        def.done(function (value) {
            $('#galleryImages1').hide();
            renderSankey(value)
        }).fail(function () {
            $('#galleryImages1').hide();
            $("#stackedGraph").html('<div style="text-transform: capitalize;text-align: center;" class="mt15">&nbsp;&nbsp;<i class="fa fa-exclamation-triangle fa-4 "></i> No records to display.  &nbsp;&nbsp;</div>');

        });

    }

    function custom_sort(a, b) {
        var aName = a.toLowerCase();
        var bName = b.toLowerCase();
        return ((aName < bName) ? -1 : ((aName > bName) ? 1 : 0));
    }

    /*function colores_google(n) {
     var colores_g = ["#DC3912","#2CA02C", "#FF7F0E", "#E7BA52", "#990099","#3366cc", "#dc3912", "#ff9900", "#109618", "#990099", "#0099c6", "#dd4477"];
     return colores_g[n % colores_g.length];
     }*/



    function renderSankey(data){
        var data1=data.data;
        var units = "Member";

        var col=new Object();


        $.each(data.levels.sort(custom_sort),function(ind,val) {
                    col[val]=colores_g[val];
                }
        );




        // set the dimensions and margins of the graph
        var margin = {top: 50, right: 60, bottom: 50, left: 20},
                width = 800 - margin.left - margin.right,
                height = 400 - margin.top - margin.bottom;

        // format variables
        var formatNumber = d3.format(",.0f"),    // zero decimal places
                format = function(d) { return formatNumber(d) + " " + units; },
//                 color = d3.scaleOrdinal(["#01A46D","#FF9B2B","#EC3E40"]);
                color = d3.scaleOrdinal(["#FF0000","#F48E9F","#A9D08E"]);

        // append the svg object to the body of the page
        var svg = d3.select("#stackedGraph").append("svg")
                .attr("width", width + margin.left + margin.right)
                .attr("height", height + margin.top + margin.bottom)
                .append("g")
                .attr("transform",
                "translate(" + margin.left + "," + margin.top + ")");

        // Set the sankey diagram properties
        var sankey = d3.sankey()
                .nodeWidth(26)
                .nodePadding(40)
                .size([width, height]);

        var path = sankey.link();

        // load the data
        //    d3.json("sankey.json", function(error, graph) {


        graph=data1;
        sankey
                .nodes(graph.nodes)
                .links(graph.links)
                .layout(32);

//         console.log(graph.links);

        // add in the links
        var link = svg.append("g").selectAll(".linkNodes")
                .data(graph.links)
                .enter().append("g").attr("class", "linkNodes")


        link.append("svg:a")
                .attr("data-href", function(d,i){
                    return createZ5Link(d.flowLink);
                })
                .attr("onclick", "postRequestForGet(this);return false;")
                .append("path")
                .attr("class", "link")
                .style("stroke", function(d) {
                    return col[d.source.name]
                })
                .attr("d", path)
                .style("stroke-width", function(d) { return Math.max(0, d.dy); })
//                .sort(function(a, b) { return b.dy - a.dy; });

        // add the link titles
        link.append("title")
                .text(function(d) {
                    return d.source.name + " → " +
                            d.target.name + "\n" + format(d.value);
                });

        // add in the nodes
        var node = svg.append("g").selectAll(".node")
                .data(graph.nodes)
                .enter().append("g")
                .attr("class", "node")
                .attr("transform", function(d) {
                    return "translate(" + d.x + "," + d.y + ")"; });
                /*.call(d3.drag()
                        .subject(function(d) {
                            return d;
                        })
                        .on("start", function() {
                            this.parentNode.appendChild(this);
                        })
                        .on("drag", dragmove)
        );*/

        // add the rectangles for the nodes
        node.append("svg:a")
                .attr("data-href", function(d,i){
                    return createZ5Link(d.sedimentLink);
                })
                .attr("onclick", "postRequestForGet(this);return false;")
                .append("rect")
                .attr("height", function(d) {
                    return d.dy; })
                .attr("width", sankey.nodeWidth())
                .style("fill", function(d) {
                    return d.color = col[d.name];
//                     return d.color = color(d.name.replace(/ .*/, ""));
                })
                .style("stroke", function(d) {
                    return d3.rgb(d.color).darker(2); })
                .append("title")
                .append("h6")
                .text(function(d) {
                    return "Total:\n" + format(d.value)+ "\nNewly Enrolled:\n" + format(d.total-d.sumvalue)+"\n"
                });


        // add in the title for the nodes
        node.append("text")
                .attr("x", -6)
                .attr("y", function(d) { return d.dy / 2; })
                .attr("dy", ".25em")
                .attr("text-anchor", "end")
                .attr("transform", null)
                .attr("class","textClass")
//                .style("text-transform","capitalize")
                .text(function(d) { return d.name; })
                .filter(function(d) { return d.x < width / 2; })
                .attr("x", 6 + sankey.nodeWidth())
                .attr("text-anchor", "start")

        var years=["last"," ","current"];


        var nodess = svg.append("g").selectAll(".nodes")
//                 .data([graph.nodes[0],graph.nodes[3],graph.nodes[6]])
                .data([2,349,696])
                .enter().append("g").attr("class", "nodes").attr("transform", function(d) {
                    return "translate(" + (d) + "," + 0 + ")"; })

        nodess.append("text")
                .attr("x", 26)
                .attr("y", function(d) { return -30 ; })
                .attr("dy", ".85em")
                .attr("text-anchor", "end")
                .attr("transform", null)
                .attr("class","textClass1")
//                 .style("text-transform","capitalize")
                .text(function(d,i) {
                    return data.year[years[i]];
                })
//                .filter(function(d) { return d.x < width / 2; })
//                .attr("x", 6 + sankey.nodeWidth())
//                .attr("text-anchor", "start")

        // the function for moving the nodes
        function dragmove(d) {
            d3.select(this).attr("transform",
                    "translate(" + (
                            d.x = Math.max(0, Math.min(width - d.dx, d3.event.x))
                    )
                    + "," + (
                            d.y = Math.max(0, Math.min(height - d.dy, d3.event.y))
                    ) + ")");
            sankey.relayout();
            link.attr("d", path);
        }

    }



</script>
<link rel="stylesheet" type="text/css" href="${resource(dir: 'css', file: 'graph2.css')}">

<style type="text/css">

.textClass{
    text-transform: capitalize;
}
.textClass1{
    font-weight: bold;
    font-size: 14px;
}
.node rect {
    fill-opacity: .9;
    shape-rendering: crispEdges;
}

.node text {
    pointer-events: none;
    text-shadow: 0 1px 0 #fff;
}

.link {
    fill: none;
    stroke: #000;
    stroke-opacity: .5;
}

.link:hover {
    stroke-opacity: .8;
}

.pathA{
    stroke:blue;
}
.pathB{
    stroke:steelblue;
}
.pathC{
    stroke:orange;
}

</style>
</body>

</html>